channels:
- anaconda
- conda-forge
- pytorch
dependencies:
- python=3.7.9
- pip=20.2.4
- pip:
  - mlflow
  - adal==1.2.7
  - applicationinsights==0.11.10
  - argcomplete==2.0.0
  - attrs==22.1.0
  - azure-common==1.1.28
  - azure-core==1.26.0
  - azure-graphrbac==0.61.1
  - azure-identity==1.11.0
  - azure-mgmt-authorization==2.0.0
  - azure-mgmt-containerregistry==10.0.0
  - azure-mgmt-core==1.3.2
  - azure-mgmt-keyvault==10.1.0
  - azure-mgmt-resource==21.1.0
  - azure-mgmt-storage==20.0.0
  - azure-storage-blob==12.13.0
  - azure-storage-queue==12.4.0
  - azureml-automl-core==1.46.1
  - azureml-automl-runtime==1.46.1
  - azureml-core==1.46.0
  - azureml-dataprep==4.5.7
  - azureml-dataprep-native==38.0.0
  - azureml-dataprep-rslex==2.11.4
  - azureml-dataset-runtime==1.46.0
  - azureml-inference-server-http==0.7.6
  - azureml-mlflow==1.46.0
  - azureml-pipeline-core==1.46.0
  - azureml-responsibleai==1.46.0
  - azureml-telemetry==1.46.0
  - azureml-train-automl-client==1.46.0
  - azureml-train-core==1.46.0
  - azureml-train-restclients-hyperdrive==1.46.0
  - azureml-training-tabular==1.46.1
  - backcall==0.2.0
  - backports-tempfile==1.0
  - backports-weakref==1.0.post1
  - bcrypt==4.0.0
  - bokeh==2.4.3
  - boto==2.49.0
  - cachetools==5.2.0
  - charset-normalizer==2.1.1
  - configparser==3.7.4
  - contextlib2==21.6.0
  - cython==0.29.17
  - dask==2.30.0
  - databricks-cli==0.17.3
  - dataclasses==0.6
  - debugpy==1.6.3
  - decorator==5.1.1
  - dice-ml==0.8
  - dill==0.3.5.1
  - distributed==2.30.1
  - distro==1.7.0
  - docker==5.0.3
  - dotnetcore2==3.1.23
  - dowhy==0.7.1
  - econml==0.13.1
  - entrypoints==0.4
  - erroranalysis==0.3.11
  - fairlearn==0.7.0
  - fire==0.4.0
  - flask==2.1.3
  - flask-cors==3.0.10
  - flatbuffers==22.9.24
  - fsspec==2022.8.2
  - gensim==3.8.3
  - gitdb==4.0.9
  - gitpython==3.1.28
  - google-api-core==2.10.2
  - google-auth==2.12.0
  - googleapis-common-protos==1.56.4
  - gunicorn==20.1.0
  - h5py==3.7.0
  - heapdict==1.0.1
  - humanfriendly==10.0
  - importlib-metadata==4.13.0
  - importlib-resources==5.9.0
  - inference-schema==1.4.2.1
  - interpret-community==0.27.0
  - interpret-core==0.2.7
  - ipykernel==6.6.0
  - ipython==7.34.0
  - isodate==0.6.1
  - itsdangerous==2.1.2
  - jedi==0.18.1
  - jeepney==0.8.0
  - jinja2==2.11.2
  - json-logging-py==0.2
  - jsonpickle==2.2.0
  - jsonschema==4.16.0
  - jupyter-client==7.3.5
  - jupyter-core==4.11.1
  - keras2onnx==1.6.0
  - knack==0.9.0
  - lightgbm==3.2.1
  - locket==1.0.0
  - markupsafe==2.0.1
  - matplotlib-inline==0.1.6
  - ml-wrappers==0.2.2
  - mlflow-skinny==1.29.0
  - mpmath==1.2.1
  - msal==1.20.0
  - msal-extensions==1.0.0
  - msgpack==1.0.4
  - msrest==0.7.1
  - msrestazure==0.6.4
  - ndg-httpsclient==0.5.1
  - nest-asyncio==1.5.6
  - networkx==2.5
  - nimbusml==1.8.0
  - numba==0.55.2
  - oauthlib==3.2.1
  - onnx==1.12.0
  - onnxconverter-common==1.6.0
  - onnxmltools==1.4.1
  - onnxruntime==1.11.1
  - opencensus==0.11.0
  - opencensus-context==0.1.3
  - opencensus-ext-azure==1.1.7
  - paramiko==2.11.0
  - parso==0.8.3
  - partd==1.3.0
  - pathspec==0.10.1
  - patsy==0.5.2
  - pexpect==4.8.0
  - pickleshare==0.7.5
  - pkginfo==1.8.3
  - pkgutil-resolve-name==1.3.10
  - pmdarima==1.7.1
  - portalocker==2.5.1
  - prompt-toolkit==3.0.31
  - protobuf==3.20.3
  - ptyprocess==0.7.0
  - pyarrow==9.0.0
  - pyasn1==0.4.8
  - pyasn1-modules==0.2.8
  - pydot==1.4.2
  - pygments==2.13.0
  - pyjwt==2.5.0
  - pynacl==1.5.0
  - pyrsistent==0.18.1
  - pyyaml==6.0
  - pyzmq==24.0.1
  - raiutils==0.2.0
  - requests==2.28.1
  - requests-oauthlib==1.3.1
  - responsibleai==0.22.0
  - rsa==4.9
  - scipy==1.5.3
  - secretstorage==3.3.3
  - semver==2.13.0
  - skl2onnx==1.4.9
  - sklearn-pandas==1.7.0
  - slicer==0.0.7
  - smart-open==1.9.0
  - smmap==5.0.0
  - sortedcontainers==2.4.0
  - sparse==0.13.0
  - sqlparse==0.4.3
  - statsmodels==0.11.1
  - sympy==1.10.1
  - tabulate==0.9.0
  - tblib==1.7.0
  - termcolor==2.0.1
  - toolz==0.12.0
  - tornado==6.2
  - traitlets==5.4.0
  - wcwidth==0.2.5
  - websocket-client==1.4.1
  - werkzeug==2.2.2
  - wrapt==1.12.1
  - zict==2.2.0
  - zipp==3.8.1
  - azureml-train-automl-runtime==1.46.1
  - azureml-interpret==1.46.0
  - azureml-defaults==1.46.0
- numpy~=1.21.6
- py-cpuinfo=5.0.0
- mpi4py=3.1.3
- click<8.0.0
- pystan=2.19.1.1
- boto3=1.15.18
- botocore=1.18.18
- joblib=0.14.1
- cloudpickle=1.6.0
- scikit-learn=0.22.1
- pandas~=1.1.5
- py-xgboost=1.3.3
- fbprophet=0.7.1
- holidays=0.10.3
- setuptools-git
- psutil>5.0.0,<6.0.0
- _libgcc_mutex=0.1
- _openmp_mutex=4.5
- _py-xgboost-mutex=2.0
- arviz=0.11.2
- binutils_impl_linux-64=2.31.1
- binutils_linux-64=2.31.1
- blas=2.106
- brotli=1.0.9
- brotli-bin=1.0.9
- brotlipy=0.7.0
- bzip2=1.0.8
- c-ares=1.18.1
- ca-certificates=2022.07.19
- certifi=2022.6.15
- cffi=1.15.1
- cftime=1.5.1.1
- click=7.1.2
- convertdate=2.3.2
- cryptography=37.0.1
- curl=7.84.0
- cycler=0.11.0
- ephem=4.1.2
- fonttools=4.25.0
- freetype=2.11.0
- gcc_impl_linux-64=7.3.0
- gcc_linux-64=7.3.0
- giflib=5.2.1
- gxx_impl_linux-64=7.3.0
- gxx_linux-64=7.3.0
- hdf4=4.2.13
- hdf5=1.10.6
- idna=3.3
- jmespath=0.10.0
- jpeg=9e
- kiwisolver=1.4.2
- korean_lunar_calendar=0.2.1
- krb5=1.19.2
- lcms2=2.12
- ld_impl_linux-64=2.33.1
- libblas=3.9.0
- libbrotlicommon=1.0.9
- libbrotlidec=1.0.9
- libbrotlienc=1.0.9
- libcblas=3.9.0
- libcurl=7.84.0
- libedit=3.1.20210910
- libev=4.33
- libffi=3.3
- libgcc-ng=12.1.0
- libgfortran-ng=11.2.0
- libgfortran5=11.2.0
- liblapack=3.9.0
- liblapacke=3.9.0
- libnetcdf=4.8.1
- libnghttp2=1.46.0
- libopenblas=0.3.12
- libpng=1.6.37
- libssh2=1.10.0
- libstdcxx-ng=11.2.0
- libtiff=4.2.0
- libwebp=1.2.2
- libwebp-base=1.2.2
- libxgboost=1.3.3
- libzip=1.8.0
- libzlib=1.2.12
- llvm-openmp=14.0.4
- llvmlite=0.38.1
- lunarcalendar=0.0.9
- lz4-c=1.9.3
- matplotlib-base=3.5.1
- mpi=1.0
- mpich=4.0.2
- munkres=1.1.4
- ncurses=6.3
- netcdf4=1.5.7
- numpy=1.21.6
- openssl=1.1.1q
- packaging=21.3
- pandas=1.1.5
- pillow=9.2.0
- psutil=5.9.0
- pycparser=2.21
- pymeeus=0.5.11
- pyopenssl=22.0.0
- pyparsing=3.0.4
- pysocks=1.7.1
- python-dateutil=2.8.2
- python_abi=3.7
- pytz=2022.1
- readline=8.1.2
- s3transfer=0.3.6
- setuptools=61.2.0
- setuptools-git=1.2
- shap=0.39.0
- six=1.16.0
- sqlite=3.39.2
- tk=8.6.12
- tqdm=4.64.0
- typing-extensions=4.3.0
- typing_extensions=4.3.0
- urllib3=1.25.11
- wheel=0.37.1
- xarray=0.20.1
- xz=5.2.5
- zlib=1.2.12
- zstd=1.5.2
- numpy==1.21.6
- pandas==1.1.5
- scikit-learn==0.22.1
- py-xgboost==1.3.3
- fbprophet==0.7.1
- holidays==0.10.3
- psutil==5.9.0
name: project_environment
